apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: taskmanager-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
